add clusters data source
instaclustr/terraform-provider-instaclustr pull request #122
Opened 2021-08-08 22:44 UTC by mootpt

This is based on: https://developer.instaclustr.com/#operation/listAllUserClusters

Seems like there were some inconsistencies between the request body schema [here]( https://developer.instaclustr.com/#operation/extendedProvisionRequestHandler) and the response body [here]( https://developer.instaclustr.com/#operation/listAllUserClusters).

A future implementation may instead retrieve all active cluster ids and use [this](https://developer.instaclustr.com/#operation/clusterDetailsTerraformHandler). Though it would be better if the API response for List Active Cluster was consistent with the [cluster status for terraform imports](https://developer.instaclustr.com/#operation/clusterDetailsTerraformHandler).

None the less, this PR works for our use case as we just need a way to iterate over all the clusterIds for a few resources.

2021-08-11 04:06 UTC, Chrismelba-Instaclustr commented
Thanks @mootpt for this contribution. I agree that this PR could be made even more useful if we made some back-end changes to our API return more information.

If you're ok to wait, we will take this into the instaclustr backlog to prioritise backend API updates that will allow us to expand the intent of this ticket.

I know you're in contact with support@instaclustr.com, so feel free to reach out to either them or here as we work through this feature.

2021-10-22 02:00 UTC, arjunrajinstaclustr commented
Yes that sounds good, we shall begin reviewing this along to bring this change in now, while trying to keep forward compatibility in mind.

2021-10-22 02:14 UTC, arjunrajinstaclustr requested changes
Thanks for the awesome PR! Left some minor comments in.

There's also a version bump in the makefile that needs to be done in this change before we can update the provider.

Just some heads up - since we usually add acceptance tests for new features, but the acceptance tests have a cost associated with them, we will shortly make a pull request to your repository with the acceptance test added so we can get the test in before merging this change.

2021-10-22 02:14 UTC, arjunrajinstaclustr commented on instaclustr/data_source_clusters.go
> +		cluster := make(map[string]interface{})
Please ignore if too hard - but could we use `mapstructure` to map the response model to the schema?

```
mapstructure.Decode(c, &cluster)
```

might do the trick, provided that the `ClusterListItem` has the required mapstructure metadata (see `ClusterProvider` for example)

2021-10-22 02:14 UTC, arjunrajinstaclustr commented on instaclustr/data_source_clusters.go
> +						"cassandra_version": {
Do you have a current need for this field? Else for forward compatibility purposes for when we decide to properly hook in the right APIs and schema to this data source, could we remove `cassandra_version` ?

2021-12-14 06:43 UTC, arjunrajinstaclustr commented on instaclustr/data_source_clusters.go
> +func dataSourceClustersList() *schema.Resource {
Added the docs

2021-12-14 06:43 UTC, arjunrajinstaclustr commented on instaclustr/data_source_clusters.go
> +						"cassandra_version": {
Removed this field

2021-12-14 06:43 UTC, arjunrajinstaclustr approved these changes

2021-12-14 22:11 UTC, michael-carter-instaclustr approved these changes

2021-12-15 02:23 UTC, merged