INS-20920: PostgreSQL APIv2
instaclustr/terraform-provider-instaclustr pull request #227
Opened 2022-12-02 03:42 UTC by Quintero-daniel

2022-12-06 03:57 UTC, peter-toms approved these changes

2022-12-09 03:06 UTC, tharinduamila-insta requested changes
there are many more attributes that need immutable set to them

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +*___pci_compliance_mode___*<br>
Given we do not have PCI compliance do we even need this option?

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +<ins>Type</ins>: nested block, required, updatable, see [intra_data_centre_replication](#nested--intra_data_centre_replication) for nested schema<br>
This should be immutable

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +<ins>Type</ins>: repeatable nested block, optional, immutable, see [tag](#nested--tag) for nested schema<br>
why is this immutable? I thought we can do tags afterwards

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +<ins>Type</ins>: nested block, optional, updatable, see [inter_data_centre_replication](#nested--inter_data_centre_replication) for nested schema<br>
again immutable

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +<ins>Type</ins>: nested block, optional, updatable, see [pg_bouncer](#nested--pg_bouncer) for nested schema<br>
Immutable

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +<ins>Type</ins>: boolean, required, updatable<br>
this should be immutable for customers and might be updated by us

2022-12-09 03:06 UTC, tharinduamila-insta commented on docs/resources/postgresql_cluster_v2.md
> +<ins>Type</ins>: string, required, updatable<br>
immutable?

2022-12-09 05:09 UTC, tharinduamila-insta approved these changes

2022-12-11 23:03 UTC, arjunrajnetapp approved these changes

2023-01-09 01:33 UTC, merged