INS 21572 role based access to KC via APIv2
instaclustr/terraform-provider-instaclustr pull request #236
Opened 2023-01-10 04:17 UTC by jacobhuanginstaclustr

2023-01-10 04:54 UTC, debaditya-netapp approved these changes

2023-01-11 04:06 UTC, arjunrajnetapp requested changes

2023-01-11 04:06 UTC, arjunrajnetapp commented on Makefile
> +VERSION=1.29.1
Should be v2.0.16

2023-01-12 03:25 UTC, WeiXinFam-Insta reviewed
Where's the info on if no access key/secret key nor iam role provided, will be the attach permission policy method by default?

2023-01-15 23:02 UTC, jacobhuanginstaclustr commented
> 

It is included in the resource documentation.

2023-01-15 23:06 UTC, jacobhuanginstaclustr commented on Makefile
> +VERSION=1.29.1
Fixed it :)

2023-01-15 23:43 UTC, arjunrajnetapp approved these changes

2023-01-16 01:01 UTC, merged