INS-23244-redis-6.0.12.redis.7.0.11
instaclustr/terraform-provider-instaclustr pull request #296
Opened 2023-06-15 02:25 UTC by niluka-insta

2023-06-15 02:41 UTC, carlsandland submitted a review, later dismissed
looks fine

2023-06-15 02:48 UTC, lyvo-instaclustr approved these changes

2023-06-15 11:27 UTC, lyvo-instaclustr requested changes
please bump up the version

2023-06-16 01:40 UTC, niluka-insta commented on Makefile
Seems we have missed bumping version to `49` . Looking at https://registry.terraform.io/providers/instaclustr/instaclustr/latest/docs it looks like `50` is the current version

2023-06-16 01:59 UTC, carrie-instaclustr approved these changes

2023-06-16 02:00 UTC, lyvo-instaclustr approved these changes

2023-06-16 02:28 UTC, carrie-instaclustr approved these changes

2023-06-16 02:28 UTC, lyvo-instaclustr approved these changes

2023-06-19 03:15 UTC, merged