INS-26168 redis version upgrade to 6.2.14 and 7.0.14
instaclustr/terraform-provider-instaclustr pull request #357
Opened 2023-12-05 02:37 UTC by johnmjkim

this pull request is for INS-26168

2023-12-05 05:28 UTC, niluka-insta requested changes
Merge conflict

2023-12-08 02:44 UTC, carrie-instaclustr approved these changes

2023-12-08 02:46 UTC, johnmjkim reviewed
I changed the version to 2.0.89

2023-12-08 03:00 UTC, niluka-insta approved these changes

2023-12-08 03:22 UTC, niluka-insta approved these changes
LGTM

2023-12-08 03:24 UTC, carrie-instaclustr approved these changes

2023-12-10 18:40 UTC, ankit-agrawal26 approved these changes

2023-12-11 04:25 UTC, merged