Adding Kafka EBS nodes
instaclustr/terraform-provider-instaclustr pull request #372
Opened 2024-03-07 00:00 UTC by RussDavidson-InstaClustr

2024-03-07 02:57 UTC, yuzhouchen-instaclustr approved these changes

2024-03-07 03:17 UTC, debaditya-netapp approved these changes

2024-03-07 03:18 UTC, debaditya-netapp requested changes
We need to update the version.

2024-03-13 00:31 UTC, debaditya-netapp approved these changes

2024-03-13 00:34 UTC, parislarkins approved these changes

2024-03-13 02:53 UTC, merged