Dedicated zookeeper support
instaclustr/terraform-provider-instaclustr pull request #45
Opened 2020-08-26 04:09 UTC by h3nd24

Added bundle option during cluster creation for the (soon to be released) Kafka feature of dedicated Zookeeper nodes

2020-08-27 09:43 UTC, williamreynoldsinstaclustr submitted a review, later dismissed

2020-09-07 06:47 UTC, h3nd24 commented on examples/main.tf
> +resource "instaclustr_cluster" "example_kafka_dedicated_zookeeper" {
Yep I can, I just thought initially to create a separate one for clarity. Will do that.

2020-09-07 06:48 UTC, h3nd24 commented on instaclustr/resource_cluster.go
> +	nodeSize := ""
Yeah that is the case currently. That's why we need to filter that out.

2020-09-07 06:50 UTC, h3nd24 commented on test/resource_cluster_test.go
> +func testKafkaDedicatedZookeeper(resourceName, hostname, username, apiKey, kafkaNodeSize, zookeeperNodeSize string) resource.TestCheckFunc {
That maybe a good idea to combine the cluster for test user resource to be the same as the dedicated zookeeper one. Will do that. For the programatic commenting, I just thought it is more compact to have it in one .tf file. Obviously I can expand it, but then there will be several files with really similar contents. Happy for discussion.

2020-09-08 05:13 UTC, arjunrajshekhar commented on instaclustr/resource_cluster.go
> +	nodeSize := ""
Understood, thanks for clarifying!

2020-09-18 01:48 UTC, h3nd24 commented on instaclustr/resource_cluster.go
> +										Type:     schema.TypeBool,
not even sure how did that happen, thanks for notifying

2020-09-23 06:05 UTC, arjunrajshekhar requested changes
Looks good, thanks! Could the build version on the makefile please be bumped to v1.4.0? We should be good to go after that!

2020-09-24 00:19 UTC, arjunrajshekhar approved these changes

2020-09-24 06:50 UTC, peter-toms approved these changes

2020-09-27 23:52 UTC, merged